### PR TITLE
Remove 'UserIdGroupPairs" list from IP Permissions

### PR DESCRIPTION
**Pull request by darahayes**
Ensures compatibility with latest changes to the aws-sg-container

### CODE REVIEW

**Comment by mcollina** [comment]
I would like to **not** have an 'aws' branch for this. Can we merge everything into v0.14?

**Comment by darahayes** [comment]
Sure thing this PR does that. https://github.com/nearform/sudc-system/pull/7

**Comment by mcollina** [comment]
This PR is against the `aws` branch here, can you merge this thing into #7? Then we merge everything into https://github.com/nearform/sudc-system/pull/4?

**Comment by darahayes** [comment]
oh right #7 already has the small change here as well as some small tidying up with the files.

**Comment by mcollina** [comment]
So, can I close this and let #7 into #4?

**Comment by darahayes** [comment]
Yup

**Pull request closed without merging**
