### PR TITLE
V0.14

### PR DESCRIPTION
**Pull request by darahayes**
Instead of having an AWS branch and a v0.14 branch, now we can compile and deploy to either the development target or AWS using just this branch

### CODE REVIEW

**Comment by mcollina** [comment]
System.json should not be in there anymore, I think.

As for the rest, it's good to go :).

**Comment by darahayes** [comment]
@mcollina Can we get this merged?

**Comment by mcollina** [comment]
We'll get this merged when v0.14 is released.

**Comment by darahayes** [comment]
Okay It's just that the current aws branch does not work with v0.14. This one can be deployed both to aws and to development with v0.14 with no problems

**Pull request merged**
